language: python
python:
    - 3.7.10
services:
    - postgresql
install:
    - pip install -r requirements.txt
script:
    - python manage.py test
deploy:
    provider: heroku
    api_key: 8bea7ef5-c2d6-43be-92f1-bd9d5fe359e5
    app: djangochattesttask
    run: python manage.py migrate
    on: master
