# Generated by Django 3.1.7 on 2021-04-08 12:19

import api.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_author_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='author',
            field=models.CharField(max_length=30, null=True, validators=[api.validators.validate_email]),
        ),
        migrations.DeleteModel(
            name='Author',
        ),
    ]
