# Generated by Django 3.2 on 2021-04-09 15:34

import api.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20210408_1419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='author',
            field=models.CharField(default='Unknown user', max_length=30, validators=[api.validators.validate_email]),
        ),
        migrations.AlterField(
            model_name='message',
            name='content',
            field=models.CharField(default='Nothing to see...', max_length=100, validators=[api.validators.validate_message]),
        ),
    ]
